# ----
# Site

title: 不那么新的C++标准学习笔记
url: "https://cxxstd.minidump.info"
baseurl:
google_analytics_key: UA-52155080-1 
show_full_navigation: true
creator:  <a href="https://minidump.info" target="_blank">@missdeer</a>

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: 学习C++11/14/17等的一点记录
author:
  name: missdeer
  email: me@minidump.info
  twitter: missdeer

comment:
    valine:
        id: g0mzo0XbC3fdm9x3QozgEF45-gzGzoHsz
        key: 5nIWNiYeU0fqd2YpoVzF4Bir

# -----
# Build

permalink: pretty

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
  docs:
    title: Documentation
    permalink: /:path/
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "docs"
    values:
      seo:
        type: Article
      _comments:
        category: Group navigation links with this field
        order: Used to sort links in the navigation
  -
    scope:
      path: ""
      type: "posts"
    values:
      _comments:
        type: Marks the impact of this release

# -----------
# CloudCannon

types:
  - minor
  - major
